---
apiVersion: v1
kind: Service
metadata:
  name: clamd-service
spec:
  selector:
    pod: clamd
  ports:
    - port: 3310
      protocol: TCP
      targetPort: 3310

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamd
spec:
  replicas: {{ .Values.clamd.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      pod: clamd
  template:
    metadata:
      name: clamd
      labels:
        pod: clamd
    spec:
      containers:
        - name: clamd
          image: {{ .Values.image }}
          imagePullPolicy: Always
          args: ["clamd"]
          ports:
            - containerPort: 3310
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 101
          volumeMounts:
            - name: clamd-database
              mountPath: /var/lib/clamav/
          resources:
            requests:
              cpu: {{ .Values.clamd.requests.cpu }}
              memory: {{ .Values.clamd.requests.memory }}
            limits:
              cpu: {{ .Values.clamd.limits.cpu }}
              memory: {{ .Values.clamd.limits.memory }}
          readinessProbe:
            tcpSocket:
              port: 3310
            timeoutSeconds: 5
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 3310
            timeoutSeconds: 5
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1
        - name: freshclam
          image: {{ .Values.image }}
          imagePullPolicy: Always
          args: ["freshclam"]
          env:
            - name: CLAMD_HOST
              value: {{ .Values.freshclam.clamdHost }}
            - name: CLAMD_PORT
              value: {{ .Values.freshclam.clamdPort | quote }}
            - name: WAIT_FOR_CLAMD
              value: {{ .Values.freshclam.waitForClamd | quote }}
            - name: FRESHCLAM_CHECKS
              value: {{ .Values.freshclam.freshclamChecks | quote }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 101
          volumeMounts:
            - name: clamd-database
              mountPath: /var/lib/clamav/
          resources:
            requests:
              cpu: {{ .Values.freshclam.requests.cpu }}
              memory: {{ .Values.freshclam.requests.memory }}
            limits:
              cpu: {{ .Values.freshclam.limits.cpu }}
              memory: {{ .Values.freshclam.limits.memory }}
      volumes:
        - name: clamd-database
          emptyDir: {}

{{- if .Values.clamd.disruptionBudget }}
---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: clamd-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      pod: clamd
{{- end }}